<<<<<<< HEAD
#include "background_substraction.h"

#include <iostream>
#include <opencv2/features2d.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/opencv.hpp>
#include <opencv2/calib3d.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/video/background_segm.hpp>

#include <math.h>

using namespace std;
using namespace cv;

void test_background_substraction() {
	//http://docs.opencv.org/trunk/d1/dc5/tutorial_background_subtraction.html

	Mat frame; //current frame
	Mat fgMaskMOG2; //fg mask fg mask generated by MOG2 method
	Ptr<BackgroundSubtractor> pMOG2; //MOG2 Background subtractor
	char keyboard; //input from keyboard

	//create GUI windows
	namedWindow("Frame");
	namedWindow("FG Mask MOG 2");
	//create Background Subtractor objects
	pMOG2 = createBackgroundSubtractorMOG2(); //MOG2 approach
}
=======
#include "opencv2/imgcodecs.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/videoio.hpp"
#include <opencv2/highgui.hpp>
#include <opencv2/video.hpp>
//C
#include <stdio.h>
//C++
#include <iostream>
#include <sstream>

using namespace cv;
using namespace std;

#include "background_substraction.h"

void test_bs() {
	Mat frame; //current frame
	Mat fgMaskMOG2; //fg mask fg mask generated by MOG2 method
	Ptr<BackgroundSubtractor> pMOG2; //MOG2 Background subtractor
	int keyboard; //input from keyboard
	cout << "We are in test_bs()" << endl;
	namedWindow("Frame");
	namedWindow("FG Mask");
	pMOG2 = createBackgroundSubtractorMOG2(); //MOG2 approach
}
>>>>>>> de2fd2dbadfc1845415ec5cfc0f8ee3da74c835d
